{{- if .Values.jbook.enabled -}}
{{- if .Values.jbook.persistenceDisk.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-lab-jbook-ebs-volume
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "gp2"
  capacity:
    storage: {{ .Values.jbook.persistenceDisk.AWS_ElasticBlockStore_size }}
  awsElasticBlockStore:
    volumeID: {{ .Values.jbook.persistenceDisk.AWS_ElasticBlockStore_volumeID }}
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-lab-jbook-ebs-volume-clain
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "gp2"
  volumeName: {{ .Release.Name }}-lab-jbook-ebs-volume
  resources:
    requests:
      storage: {{ .Values.jbook.persistenceDisk.AWS_ElasticBlockStore_size }}
# {{- else }}
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: {{ .Release.Name }}-lab-jbook-ebs-volume-clain
#   namespace: {{ .Values.namespace }}
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: "gp2"
#   resources:
#     requests:
#       storage: 20Gi
{{- end }}
{{- end }}
